"""DVC featurize stage: temporal split raw parquet → train/test feature parquets."""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd
import yaml

logger = logging.getLogger(__name__)


def _load_params(params_path: str = "params.yaml") -> dict:
    with open(params_path, "r") as fh:
        return yaml.safe_load(fh)


def featurize(
    raw_path: str,
    train_path: str,
    test_path: str,
    monitor_path: str,
    train_end_periodo: int,
    test_start_periodo: int,
    test_end_periodo: int,
    monitor_start_periodo: int,
    period_col: str = "periodo",
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Load raw parquet, apply three-way temporal split, save train/test/monitor sets.

    Splits:
        train   : periodo <= train_end_periodo
        test    : test_start_periodo <= periodo <= test_end_periodo
        monitor : periodo >= monitor_start_periodo  (simulates production / 2026)

    Args:
        raw_path: Path to raw parquet generated by generate_dataset.py.
        train_path: Output path for training set.
        test_path: Output path for test set.
        monitor_path: Output path for monitoring/production set.
        train_end_periodo: Upper bound YYYYMM for training (inclusive).
        test_start_periodo: Lower bound YYYYMM for test (inclusive).
        test_end_periodo: Upper bound YYYYMM for test (inclusive).
        monitor_start_periodo: Lower bound YYYYMM for monitor set (inclusive).
        period_col: Column holding the YYYYMM period.

    Returns:
        Tuple of (train_df, test_df, monitor_df).
    """
    logger.info("Loading raw data from %s", raw_path)
    df = pd.read_parquet(raw_path, engine="pyarrow")
    logger.info("Raw shape: %s | columns: %s", df.shape, list(df.columns))

    if period_col not in df.columns:
        raise KeyError(f"Period column '{period_col}' not found in dataset.")

    train_df = df[df[period_col] <= train_end_periodo].reset_index(drop=True)
    test_df = df[
        (df[period_col] >= test_start_periodo) & (df[period_col] <= test_end_periodo)
    ].reset_index(drop=True)
    monitor_df = df[df[period_col] >= monitor_start_periodo].reset_index(drop=True)

    logger.info(
        "Split: train=%d rows (periodo<=%d) | test=%d rows (%d–%d) | monitor=%d rows (periodo>=%d)",
        len(train_df), train_end_periodo,
        len(test_df), test_start_periodo, test_end_periodo,
        len(monitor_df), monitor_start_periodo,
    )

    target_col = "SeriousDlqin2yrs"
    if target_col in train_df.columns:
        logger.info(
            "Default rate — train: %.4f | test: %.4f | monitor: %.4f",
            train_df[target_col].mean(),
            test_df[target_col].mean(),
            monitor_df[target_col].mean() if len(monitor_df) > 0 else float("nan"),
        )

    for path in [train_path, test_path, monitor_path]:
        Path(path).parent.mkdir(parents=True, exist_ok=True)

    train_df.to_parquet(train_path, index=False, engine="pyarrow")
    test_df.to_parquet(test_path, index=False, engine="pyarrow")
    monitor_df.to_parquet(monitor_path, index=False, engine="pyarrow")

    logger.info("Saved train   → %s", train_path)
    logger.info("Saved test    → %s", test_path)
    logger.info("Saved monitor → %s", monitor_path)

    return train_df, test_df, monitor_df


def main() -> None:
    """CLI entry-point for the DVC featurize stage."""
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")

    parser = argparse.ArgumentParser(description="DVC featurize stage")
    parser.add_argument("--params", default="params.yaml")
    args = parser.parse_args()

    params = _load_params(args.params)
    data = params["data"]
    feat = params["features"]

    featurize(
        raw_path=data["raw_path"],
        train_path=data["train_path"],
        test_path=data["test_path"],
        monitor_path=data["monitor_path"],
        train_end_periodo=data["train_end_periodo"],
        test_start_periodo=data["test_start_periodo"],
        test_end_periodo=data["test_end_periodo"],
        monitor_start_periodo=data["monitor_start_periodo"],
        period_col=feat["period_col"],
    )


if __name__ == "__main__":
    main()
